language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.4.1
    - DJANGO=1.3.3
install:
    - pip install argparse --use-mirrors
    - pip install -q Django==$DJANGO --use-mirrors
script: python quicktest.py helpdesk
